CFG = {
    "seq_len": 512,
    "num_cls": 3,
    "level_offset": 4,
    "split": 0.8,
    "val_split": 0.1,
    "lr": 5e-4,
    "check_val_every_n_epoch": 10,
    "metric_samples": 256,
    "g4hunter_window": 25,
    "checkpoint_save_top_k": 5,
    "lstm": dict(
        emb_dim=128,
        level_dim=16,
        hidden_dim=512,
        num_layers=2,
        mlp_layers=1,
        dropout=0.3,
        sample_temperature=1.0,
        top_k=0,
    ),
    "vae": dict(
        hidden_dim=320,
        latent_dim=128,
        num_res_blocks=2,
        dropout=0.1,
        sample_temperature=0.8,
        beta=0.1,
        beta_warmup_steps=20000,
    ),
    "dfm": dict(
        hidden_dim=128,
        num_cnn_stacks=4,
        num_transformer_layers=1,
        num_attention_heads=4,
        transformer_ff_mult=1,
        dropout=0.0,
        alpha_max=8.0,
        alpha_scale=2.0,
        prior_pseudocount=2.0,
        num_integration_steps=100,
        flow_temp=1.0,
        classifier_free_guidance=True,
        cond_drop_prob=0.3,
        allow_nan_cfactor=True,
    ),
}
